services:
  alphagpo:
    build:
      context: .
    entrypoint: /app/scripts/alphagpo-entrypoint.sh
    volumes:
      - "./alphagpo-git:/app/alphagpo-git"
      - "./data/media:/tmp/alphagpo-media"
      - "./envs:/app/alphagpo-git/envs"
      - "./scripts:/app/scripts"
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - worker
      - scheduler
      - feedservice

  feedservice:
    build:
      context: .
      dockerfile: feedservice.Dockerfile
    entrypoint: /app/scripts/feedservice-entrypoint.sh
    volumes:
      - "./feedservice:/app/feedservice"
      - "./data/media:/tmp/alphagpo-media"
      - "./feedservice-envs:/app/feedservice/envs"
      - "./scripts:/app/scripts"
    ports:
      - "8080:8080"

  worker:
    build:
      context: .
    entrypoint: /app/scripts/worker-entrypoint.sh
    volumes:
      - "./alphagpo-git:/app/alphagpo-git"
      - "./data/media:/tmp/alphagpo-media"
      - "./envs:/app/alphagpo-git/envs"
      - "./scripts:/app/scripts"
    depends_on:
      - redis

  scheduler:
    build:
      context: .
    entrypoint: /app/scripts/scheduler-entrypoint.sh
    depends_on:
      - db
    volumes:
      - "./alphagpo-git:/app/alphagpo-git"
      - "./envs:/app/alphagpo-git/envs"
      - "./scripts:/app/scripts"

  db:
    image: postgres:latest
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    environment:
      - POSTGRES_DB=alphagpo
      - POSTGRES_PASSWORD=alphagpo
      - POSTGRES_USER=alphagpo
    ports:
      - "5432:5432"
  redis:
    image: redis:latest
    ports:
      - "8443:8443"
      - "9443:9443"
      - "8001:8001"
      - "12000:12000"
      - "6379:6379"
    volumes:
      - "./data/media:/tmp/alphagpo-media"
