services:
  mygpo:
    build:
      context: .
    entrypoint: /app/docker-entrypoint.sh
    volumes:
      - "./envs:/app/envs"
      - "./data/media:/tmp/mygpo-media"
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  db:
    image: postgres:latest
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    environment:
      - POSTGRES_DB=mygpo
      - POSTGRES_PASSWORD=mygpo
      - POSTGRES_USER=mygpo
  redis:
    image: redis:latest
    volumes:
      - "./data/media:/tmp/mygpo-media"
