#!/bin/bash
# Initialize the host machine for running this project.
mkdir -p ./data/postgres
mkdir -p ./data/media

# Pull in the latest code.
git clone https://github.com/gpodder/mygpo.git mygpo-git
